using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using Interlude.Conditions;
using Interlude.Model;
using Interlude.Serialization;
using Interlude.Theming;
using Interlude.Validation;

namespace Interlude.Preview;

/// <summary>
/// Writes the form schema out as Markdown, for the authoring skill in <c>skills/interlude-form</c>.
///
/// The skill's job is to turn a description of a form into a file the reader accepts, and it can
/// only do that if it knows every discriminator and every property. Hand-writing that list would
/// produce a document that is correct on the day it is written: add a control, and a skill that
/// has never heard of it keeps emitting the six it knows. So the list is generated from the same
/// place the reader gets it — the serializer's own type graph — and a test fails the build if the
/// checked-in copy has fallen behind.
///
/// Property names come from <see cref="FormJson.Options"/> rather than from the CLR names, so
/// what is documented is literally what the reader will accept, camel casing and all. The prose
/// is the XML documentation on the model, which is the same text the node help is built from.
/// </summary>
internal static class SchemaReference
{
    /// <summary>
    /// Types documented once at the end and referred to by name from the tables above, because
    /// they appear as the type of a property on a dozen different elements.
    /// </summary>
    private static readonly Type[] SupportingTypes =
    {
        typeof(FormButtons),
        typeof(WindowOptions),
        typeof(ThemeDefinition),
        typeof(ElementStyle),
        typeof(OptionItem),
    };

    internal static void Generate(string file)
    {
        Assembly assembly = typeof(FormDefinition).Assembly;
        XmlDocs docs = XmlDocs.LoadBeside(assembly);

        // Enums are collected as they are met rather than listed up front: an enum nobody's
        // property mentions is not part of the schema, whatever the assembly contains.
        SortedDictionary<string, Type> enums = new(StringComparer.Ordinal);

        StringBuilder text = new();

        text.AppendLine("# The Interlude form schema");
        text.AppendLine();
        text.AppendLine(
            "Generated from the Interlude assembly by `Interlude.Preview --schema`. Every property " +
            "here is one the reader accepts, spelled the way it accepts it. Do not edit this file.");
        text.AppendLine();
        text.AppendLine(
            $"Schema version **{FormDefinition.CurrentSchemaVersion}**. A file whose `schemaVersion` " +
            "is higher is refused outright rather than partly understood, so always write the " +
            "version above.");
        text.AppendLine();

        WriteObject(text, docs, enums, "## The document", typeof(FormDefinition));

        text.AppendLine("## Every element");
        text.AppendLine();
        text.AppendLine(
            "Each carries a `$type` naming its kind. The properties below are the ones that kind " +
            "adds; every element also has the shared ones.");
        text.AppendLine();

        WriteHierarchy(text, docs, enums, typeof(FormElement), "###", "Shared by every element");

        text.AppendLine("## Conditions");
        text.AppendLine();
        text.AppendLine(
            "The value of `visibleIf`, `enabledIf` and `requiredIf`. A condition reads the form's " +
            "own answers by key.");
        text.AppendLine();

        WriteHierarchy(text, docs, enums, typeof(ConditionExpr), "###", "Shared by every condition");

        text.AppendLine("## Computed values");
        text.AppendLine();
        text.AppendLine("The value of an input's `computed`, which makes the form own that field rather than the user.");
        text.AppendLine();

        WriteHierarchy(text, docs, enums, typeof(ComputedValue), "###", "Shared by every computed value");

        text.AppendLine("## Rules");
        text.AppendLine();
        text.AppendLine("The entries in an element's `rules`, applied while the user types.");
        text.AppendLine();

        WriteHierarchy(text, docs, enums, typeof(ValidationRule), "###", "Shared by every rule");

        text.AppendLine("## Supporting objects");
        text.AppendLine();

        foreach (Type type in SupportingTypes)
        {
            WriteProperties(text, docs, enums, type, Array.Empty<Type>(), "### " + type.Name);
        }

        WriteEnums(text, enums);

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(file))!);

        // Newline-normalised, because this file is compared against a checked-in copy by a test
        // and a CRLF difference is not a schema difference.
        File.WriteAllText(file, text.ToString().Replace("\r\n", "\n"));
        Console.WriteLine("wrote " + file);
    }

    /// <summary>
    /// Friendlier headings for the abstract types that sit between an element and the root. The
    /// name of the record is an implementation detail; what an author needs to know is which
    /// controls a shared property applies to.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, string> BaseHeadings =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["InputElement"] = "Shared by every input",
            ["DisplayElement"] = "Shared by every display element",
            ["ContainerElement"] = "Shared by every container",
            ["OptionInputElement"] = "Shared by the inputs that offer a list of options",
        };

    /// <summary>
    /// Writes one table per concrete subtype of a polymorphic base, in the order the
    /// <c>JsonDerivedType</c> attributes declare them — which groups the inputs, then the display
    /// elements, then the containers, the same order a reader of the model sees.
    ///
    /// The abstract types in between get a table each, first. Without them a property declared on
    /// one — a drop-down's <c>options</c>, a container's <c>children</c> — would be skipped as
    /// inherited from every concrete table and documented in none of them.
    /// </summary>
    private static void WriteHierarchy(
        StringBuilder text,
        XmlDocs docs,
        SortedDictionary<string, Type> enums,
        Type baseType,
        string heading,
        string rootHeading)
    {
        JsonDerivedTypeAttribute[] all = baseType.GetCustomAttributes<JsonDerivedTypeAttribute>().ToArray();

        // The root's own properties, which are shared by every one of its subtypes. Easy to forget
        // that a rule's `message` lives here rather than on each rule, and a property documented
        // nowhere is one the skill will never write.
        WriteProperties(text, docs, enums, baseType, Array.Empty<Type>(), $"{heading} {rootHeading}");

        // Shallowest first, so a reader meets InputElement before OptionInputElement refines it.
        IEnumerable<Type> intermediates = all
            .SelectMany(derived => Ancestors(derived.DerivedType, baseType))
            .Where(type => type.IsAbstract && type != baseType)
            .Distinct()
            .OrderBy(type => Ancestors(type, baseType).Length);

        foreach (Type intermediate in intermediates)
        {
            string label = BaseHeadings.TryGetValue(intermediate.Name, out string? friendly)
                ? friendly
                : intermediate.Name;

            WriteProperties(
                text, docs, enums, intermediate, Ancestors(intermediate, baseType),
                $"{heading} {label}");
        }

        foreach (JsonDerivedTypeAttribute derived in all)
        {
            string discriminator = derived.TypeDiscriminator as string
                ?? throw new InvalidOperationException(
                    $"{derived.DerivedType.Name} has a non-string type discriminator, which the " +
                    "schema reference cannot render.");

            // Everything the base already documented is skipped, so a table shows what is specific
            // to this kind rather than repeating eleven shared rows thirty-two times.
            WriteProperties(
                text, docs, enums, derived.DerivedType, Ancestors(derived.DerivedType, baseType),
                $"{heading} `{discriminator}`");
        }
    }

    private static void WriteObject(
        StringBuilder text,
        XmlDocs docs,
        SortedDictionary<string, Type> enums,
        string heading,
        Type type)
        => WriteProperties(text, docs, enums, type, Array.Empty<Type>(), heading);

    private static void WriteProperties(
        StringBuilder text,
        XmlDocs docs,
        SortedDictionary<string, Type> enums,
        Type type,
        IReadOnlyCollection<Type> inheritedFrom,
        string heading)
    {
        HashSet<string> inherited = new(
            inheritedFrom.SelectMany(SerializedProperties).Select(property => property.Name),
            StringComparer.Ordinal);

        JsonPropertyInfo[] properties = SerializedProperties(type)
            .Where(property => !inherited.Contains(property.Name))
            .ToArray();

        text.AppendLine(heading);
        text.AppendLine();

        string summary = docs.ForType(type);
        if (summary.Length > 0)
        {
            // The first paragraph only. Model summaries carry the reasoning behind a decision as
            // well as the decision, and the reasoning belongs in the source, not in a lookup table.
            text.AppendLine(summary.Split("\n\n")[0]);
            text.AppendLine();
        }

        if (properties.Length == 0)
        {
            text.AppendLine("No properties of its own.");
            text.AppendLine();
            return;
        }

        object? blank = TryInstantiate(type);

        text.AppendLine("| Property | Type | Default | Meaning |");
        text.AppendLine("| --- | --- | --- | --- |");

        foreach (JsonPropertyInfo property in properties)
        {
            PropertyInfo? reflected = property.AttributeProvider as PropertyInfo;

            text.Append("| `").Append(property.Name).Append("` | ")
                .Append(Describe(property.PropertyType, enums)).Append(" | ")
                .Append(DefaultOf(blank, reflected)).Append(" | ")
                .Append(reflected is null ? string.Empty : Cell(docs.ForProperty(reflected)))
                .AppendLine(" |");
        }

        text.AppendLine();
    }

    /// <summary>
    /// The shipped options, copied, with the reflection resolver named explicitly.
    ///
    /// <c>GetTypeInfo</c> needs a resolver, and the real options only acquire the default one when
    /// something is first serialized through them. Copying rather than mutating matters: those
    /// options are the ones every form in the process is read and written with, and attaching a
    /// resolver to them from a documentation tool would be reaching into the serializer to make a
    /// report come out.
    /// </summary>
    private static readonly JsonSerializerOptions Reflected =
        new(FormJson.Options) { TypeInfoResolver = new DefaultJsonTypeInfoResolver() };

    /// <summary>
    /// The properties the serializer will actually read and write, in its own order and under its
    /// own names. Asking the serializer rather than reflecting directly is what keeps this honest
    /// about <c>[JsonIgnore]</c> and the camel-case naming policy.
    /// </summary>
    private static IEnumerable<JsonPropertyInfo> SerializedProperties(Type type)
        => Reflected.GetTypeInfo(type).Properties.Where(IsWritten);

    /// <summary>
    /// The resolver reports a <c>[JsonIgnore]</c> property among a type's properties even though
    /// the serializer never writes one — <c>producesValue</c> is on every element and in no form
    /// file. Documenting it would send an author writing a property the reader discards, so the
    /// attribute is honoured here rather than trusted to have been.
    /// </summary>
    private static bool IsWritten(JsonPropertyInfo property)
        => property.AttributeProvider?.GetCustomAttributes(typeof(JsonIgnoreAttribute), inherit: true)
               is not { Length: > 0 };

    /// <summary>Every base type between a derived type and the polymorphic root, inclusive.</summary>
    private static Type[] Ancestors(Type derived, Type root)
    {
        List<Type> chain = new();

        for (Type? current = derived.BaseType; current is not null; current = current.BaseType)
        {
            chain.Add(current);

            if (current == root)
            {
                break;
            }
        }

        return chain.ToArray();
    }

    /// <summary>
    /// The value a property has when nothing sets it, read off a freshly-made instance.
    ///
    /// Worth the trouble because a default is the difference between a form that has to spell out
    /// every property and one that says only what is unusual about it. Not every type can be made
    /// this way — some have no parameterless constructor — and those simply show no defaults.
    /// </summary>
    private static object? TryInstantiate(Type type)
    {
        try
        {
            return type.IsAbstract ? null : Activator.CreateInstance(type);
        }
        catch (Exception ex) when (ex is MissingMethodException or TargetInvocationException or NotSupportedException)
        {
            return null;
        }
    }

    private static string DefaultOf(object? blank, PropertyInfo? property)
    {
        if (blank is null || property is null)
        {
            return string.Empty;
        }

        object? value;

        try
        {
            value = property.GetValue(blank);
        }
        catch (TargetInvocationException)
        {
            return string.Empty;
        }

        return value switch
        {
            null => "`null`",
            string empty when empty.Length == 0 => string.Empty,
            string text => "`\"" + text + "\"`",
            bool flag => flag ? "`true`" : "`false`",
            // Whole doubles are written with a decimal point, matching how the serializer writes
            // them and how the schema documents number handling.
            double number => "`" + number.ToString("0.0###", CultureInfo.InvariantCulture) + "`",
            Enum name => "`" + Camel(name.ToString()) + "`",
            IEnumerable list when !list.Cast<object?>().Any() => "empty",
            IEnumerable => string.Empty,

            // A nested object's default is its own table's worth of defaults. Printing the record's
            // ToString here puts twenty properties in one cell and tells the reader nothing they
            // could not get from the section that documents the type.
            not null when value.GetType().IsClass => "the " + value.GetType().Name + " defaults",

            _ => "`" + Convert.ToString(value, CultureInfo.InvariantCulture) + "`",
        };
    }

    /// <summary>Renders a CLR type as the JSON the reader expects there.</summary>
    private static string Describe(Type type, SortedDictionary<string, Type> enums)
    {
        Type bare = Nullable.GetUnderlyingType(type) ?? type;

        if (bare.IsEnum)
        {
            enums[bare.Name] = bare;
            return $"[{bare.Name}](#{bare.Name.ToLowerInvariant()})";
        }

        if (bare == typeof(string))
        {
            return "string";
        }

        if (bare == typeof(bool))
        {
            return "boolean";
        }

        if (bare == typeof(int) || bare == typeof(long))
        {
            return "integer";
        }

        if (bare == typeof(double) || bare == typeof(float) || bare == typeof(decimal))
        {
            return "number";
        }

        if (bare == typeof(DateTime))
        {
            return "`{ \"$date\": \"…\" }`";
        }

        if (bare == typeof(object))
        {
            // The loosely-typed ports: defaults, condition operands, option values. Worth calling
            // out rather than writing "object", because the tagging rules apply here and nowhere else.
            return "any value";
        }

        if (bare == typeof(RgbColor))
        {
            return "`{ \"$color\": \"#RRGGBB\" }`";
        }

        if (bare.IsGenericType && typeof(IEnumerable).IsAssignableFrom(bare))
        {
            return Describe(bare.GetGenericArguments()[0], enums) + "[]";
        }

        if (bare == typeof(FormElement))
        {
            return "element";
        }

        if (bare == typeof(ConditionExpr))
        {
            return "condition";
        }

        if (bare == typeof(ComputedValue))
        {
            return "computed value";
        }

        if (bare == typeof(ValidationRule))
        {
            return "rule";
        }

        return $"[{bare.Name}](#{bare.Name.ToLowerInvariant()})";
    }

    private static void WriteEnums(StringBuilder text, SortedDictionary<string, Type> enums)
    {
        text.AppendLine("## Enumerations");
        text.AppendLine();
        text.AppendLine("Written as names, camel-cased, never as numbers.");
        text.AppendLine();

        foreach ((string name, Type type) in enums)
        {
            text.Append("### ").AppendLine(name);
            text.AppendLine();
            text.AppendLine(string.Join(" ", Enum.GetNames(type).Select(value => "`" + Camel(value) + "`")));
            text.AppendLine();
        }
    }

    /// <summary>Matches the naming policy the serializer's enum converter is built with.</summary>
    private static string Camel(string name)
        => JsonNamingPolicy.CamelCase.ConvertName(name);

    /// <summary>
    /// Flattens a summary into one table cell: no newlines, and no pipe that would end the column.
    /// </summary>
    private static string Cell(string summary)
    {
        if (summary.Length == 0)
        {
            return string.Empty;
        }

        return summary.Split("\n\n")[0].Replace("\n", " ").Replace("|", "\\|").Trim();
    }
}
