"""Build-time hooks for the documentation site.

Two problems this solves, both of which come from the same place: the Markdown in `docs/` is
written to be read on GitHub *first* and rendered into a site second. It is not site-shaped
source, and a good deal of it is generated by the build and must not be edited by hand.

1. **Links that leave `docs/`.** `docs/README.md` points at `../CONTRIBUTING.md`,
   `docs/architecture.md` points at `../src/Interlude/Runtime/FormSession.cs`, and
   `docs/nodes/README.md` — which is generated — points at `../../scripts/pack.ps1`. All of those
   resolve on GitHub and none of them exist inside the site. Rather than rewrite the sources and
   break the GitHub reading path (and fight the generator every build), the links are rewritten
   here, at build time, into absolute URLs against `repo_url`.

2. **Nav for a folder of 118 generated files.** `docs/nodes/` gains a file whenever a node is
   added, and a nav listing them by hand would be stale by the next release. A nav entry whose
   value ends in `/*` is expanded into every Markdown file in that folder, index first, the rest
   alphabetical.

3. **The font the forms are actually set in.** Space Grotesk is compiled into `Interlude.dll` as a
   WPF resource and is what every form renders with. The site is set in the same faces, taken from
   the same files in `src/Interlude/Fonts/` and copied into the build — not fetched from Google
   Fonts, which would be a third-party request for a *different* file (Google distributes the
   variable font; the package vendors the static instances, for reasons written down in
   `Interlude.csproj`). Copied rather than duplicated under `docs/` so there is one copy in the
   repository and the site cannot drift from the package.

The last, smaller thing: `docs/original-brief.md` is a historical document that calls the package
by a name it no longer has. It stays in the site because the reasoning in it is still the
reasoning, but it is kept out of the search index so that searching for a control does not surface
the 2026 plan for it. That is done here rather than in front matter because front matter renders
as a table on GitHub, and this file's GitHub reading path matters more than most.
"""

from __future__ import annotations

import glob
import logging
import os
import posixpath
import re

# Named under `mkdocs.` so that --strict counts what this reports. A link out of docs/ that names
# a file no longer in the repository is exactly as broken as one inside it, and is otherwise
# invisible: MkDocs stops checking a link the moment it becomes an absolute URL.
log = logging.getLogger("mkdocs.hooks.repo_links")

# `](target)` — inline links and images alike. The target is taken up to the first whitespace or
# closing bracket, so `](path "title")` keeps its title.
LINK = re.compile(r"\]\(\s*(?P<target>[^)\s]+)(?P<rest>[^)]*)\)")

SKIP_PREFIXES = ("http://", "https://", "//", "mailto:", "#", "data:")

# Kept out of the search index. Relative to docs_dir, POSIX separators.
SEARCH_EXCLUDED = {"original-brief.md"}

# The faces shipped inside Interlude.dll, published from the one copy in src/. The licence travels
# with them: SIL OFL 1.1, and a font served without it is a licence breach however small the file.
FONT_SOURCE = ("src", "Interlude", "Fonts")
FONT_FILES = (
    "SpaceGrotesk-Light.ttf",
    "SpaceGrotesk-Regular.ttf",
    "SpaceGrotesk-Medium.ttf",
    "SpaceGrotesk-Bold.ttf",
    "SpaceGrotesk-OFL.txt",
)

# What NodeDocs.cs writes into a node page's `## Example File` section when a graph sits beside
# it: an inert filename in backticks, which is all Dynamo's own help panel needs — it resolves the
# graph by name from the package's doc/ folder. On the web there is no panel to do that, so the
# filename becomes a download link. Matched rather than reformatted so the generated file, which
# CI checks byte-for-byte, is never touched.
EXAMPLE_GRAPH = re.compile(
    r"An example graph ships beside this page as `(?P<graph>[^`]+\.dyn)`\."
)


def on_config(config, **kwargs):
    """Expand `folder/*` nav entries into the Markdown files in that folder."""
    if config.get("nav"):
        config["nav"] = _expand(config["nav"], config["docs_dir"])
    return config


def _expand(items, docs_dir):
    expanded = []
    for item in items:
        if not isinstance(item, dict):
            expanded.append(item)
            continue

        (title, value), = item.items()
        if isinstance(value, list):
            expanded.append({title: _expand(value, docs_dir)})
        elif isinstance(value, str) and value.endswith("/*"):
            expanded.append({title: _folder(value[:-2], docs_dir)})
        else:
            expanded.append(item)
    return expanded


def on_files(files, config, **kwargs):
    """Publish the package's own font files, from the package's own copy of them."""
    from mkdocs.structure.files import File

    repo_root = os.path.dirname(os.path.abspath(config["docs_dir"]))
    source = os.path.join(repo_root, *FONT_SOURCE)

    for name in FONT_FILES:
        path = os.path.join(source, name)
        if not os.path.isfile(path):
            raise FileNotFoundError(
                f"{path} is missing. The site is set in the faces the package ships; if they have "
                f"moved, update FONT_SOURCE in this file rather than pointing the CSS elsewhere."
            )
        files.append(File.generated(config, f"assets/fonts/{name}", abs_src_path=path))

    return files


def _folder(folder, docs_dir):
    found = glob.glob(os.path.join(docs_dir, folder, "*.md"))
    if not found:
        raise ValueError(f"nav refers to '{folder}/*', which matched no Markdown files")

    pages = [posixpath.join(folder, os.path.basename(path)) for path in found]
    # The folder's own index leads; everything else is alphabetical. Node help files are named
    # after the node (`Interlude.Input.TextBox.md`), so alphabetical is also grouped by category.
    pages.sort(key=lambda page: (
        posixpath.basename(page).lower() not in ("readme.md", "index.md"),
        page.lower(),
    ))
    return pages


def _link_example_graphs(markdown, page, config):
    """Turn a node page's example-graph filename into something you can click."""
    folder = os.path.join(config["docs_dir"], posixpath.dirname(page.file.src_uri))

    def rewrite(match):
        graph = match.group("graph")
        if not os.path.isfile(os.path.join(folder, graph)):
            # The section is only written when the file is there, so this should not happen. If it
            # ever does, leaving the sentence alone beats publishing a link to nothing.
            return match.group(0)
        return (
            "An example graph ships beside this page: "
            f"[{graph}]({graph})" "{ .dyn-download download }"
        )

    return EXAMPLE_GRAPH.sub(rewrite, markdown)


def on_page_markdown(markdown, page, config, **kwargs):
    """Point links that leave `docs/` at the repository they actually refer to."""
    if page.file.src_uri in SEARCH_EXCLUDED:
        page.meta["search"] = {"exclude": True}

    markdown = _link_example_graphs(markdown, page, config)

    repo_url = (config.get("repo_url") or "").rstrip("/")
    if not repo_url:
        return markdown

    branch = config.get("extra", {}).get("repo_branch", "main")
    page_dir = posixpath.dirname(page.file.src_uri)
    repo_root = os.path.dirname(os.path.abspath(config["docs_dir"]))

    def rewrite(match):
        target = match.group("target")
        # Only a link that climbs out of its own folder can leave docs/. Everything else —
        # `sibling.md`, `nodes/Foo.md`, `#anchor`, absolute URLs — MkDocs resolves itself.
        if target.startswith(SKIP_PREFIXES) or not target.startswith("../"):
            return match.group(0)

        path, _, fragment = target.partition("#")
        if not path:
            return match.group(0)

        # Where the link lands, expressed from docs_dir. A leading `../` survives normpath only
        # when the target really is outside the documentation root.
        resolved = posixpath.normpath(posixpath.join(page_dir, path))
        if not resolved.startswith("../"):
            return match.group(0)  # Still inside docs/ — MkDocs resolves it.

        # docs/ sits one level below the repository root, so exactly one `../` is consumed
        # getting there. Anything climbing further has left the repository and is not ours.
        from_root = resolved[len("../"):]
        if from_root.startswith("../"):
            return match.group(0)
        # `blob` or `tree` is decided by looking, not by guessing from the name. Several of the
        # folders these pages link to are called things like `tools/Interlude.Preview`, and any
        # rule based on "the last segment has a dot in it" gets every one of those backwards.
        on_disk = os.path.join(repo_root, *from_root.split("/"))
        if os.path.isdir(on_disk):
            kind = "tree"
        elif os.path.isfile(on_disk):
            kind = "blob"
        else:
            log.warning(
                "Doc file '%s' links to '%s', which is not in the repository.",
                page.file.src_uri, target,
            )
            kind = "tree" if path.endswith("/") else "blob"

        rebuilt = f"{repo_url}/{kind}/{branch}/{from_root}"
        if fragment:
            rebuilt += f"#{fragment}"
        return f"]({rebuilt}{match.group('rest')})"

    return LINK.sub(rewrite, markdown)
